[project]
name = "soft-crm"
version = "0.1.0"
description = "Pequeño CRM basado en multi agentes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.2.1",
    "pydantic-settings>=2.8.1",
]
